"""Mosquitto ACL policy and recoverable file transaction for VPS Sentinel 1.0."""

import fcntl
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import tempfile

from node_contract import ContractError, validate_node_id


USERNAME_PATTERN = re.compile(r"^[A-Za-z0-9_.-]{1,128}$")


class BrokerPolicyError(ValueError):
    """Raised when a Broker policy or transaction cannot be applied safely."""


def _username(value, field):
    if not isinstance(value, str) or not USERNAME_PATTERN.fullmatch(value):
        raise BrokerPolicyError(f"{field} contains an invalid MQTT username")
    return value


class BrokerPolicy:
    """Render least-privilege ACL entries for all supported deployment roles."""

    def __init__(
        self,
        enrollments,
        *,
        home_assistant_username="home-assistant",
        controller_username="vps-controller",
        legacy_bindings=None,
    ):
        self.enrollments = enrollments
        self.home_assistant_username = _username(
            home_assistant_username,
            "home_assistant_username",
        )
        self.controller_username = _username(
            controller_username,
            "controller_username",
        )
        self.legacy_bindings = legacy_bindings or {}

    def render_acl(self):
        lines = [
            "# Generated by VPS Sentinel. Manual edits will be replaced.",
            f"user {self.home_assistant_username}",
            "topic readwrite #",
            "",
            f"user {self.controller_username}",
            "topic read vps-sentinel/v1/nodes/+/+",
            "topic write vps-sentinel/v1/controller/#",
            "topic write homeassistant/#",
        ]
        for username in sorted(self.legacy_bindings):
            _username(username, "legacy username")
            node_ids = self.legacy_bindings[username]
            if not isinstance(node_ids, (list, tuple, set)) or not node_ids:
                raise BrokerPolicyError("legacy binding must contain node IDs")
            lines.extend(["", f"user {username}"])
            for node_id in sorted(set(node_ids)):
                try:
                    validate_node_id(node_id)
                except ContractError as error:
                    raise BrokerPolicyError(
                        "legacy binding contains an invalid node_id"
                    ) from error
                root = f"vps/{node_id}"
                lines.extend([
                    f"topic write {root}/#",
                    f"topic read {root}/command",
                ])
            lines.append("topic write homeassistant/#")

        enrolled_acl = self.enrollments.acl_text(
            controller_username=self.controller_username
        ).splitlines()
        for line in enrolled_acl:
            if line.startswith(f"user {self.controller_username}"):
                continue
            if line in {
                "topic read vps-sentinel/v1/nodes/+/+",
                "topic write vps-sentinel/v1/controller/#",
                "topic write homeassistant/#",
            }:
                continue
            if not line and (not lines or not lines[-1]):
                continue
            lines.append(line)
        return "\n".join(lines).rstrip() + "\n"


class BrokerFilesTransaction:
    """Stage Broker files and restore all originals when restart fails."""

    def __init__(
        self,
        *,
        password_file="/etc/mosquitto/passwd",
        acl_file="/etc/mosquitto/vps-sentinel.acl",
        config_file="/etc/mosquitto/conf.d/home-assistant.conf",
        runner=None,
        restarter=None,
        chown=None,
    ):
        self.password_file = Path(password_file)
        self.acl_file = Path(acl_file)
        self.config_file = Path(config_file)
        self.runner = runner or self._run
        self.restarter = restarter or self._restart
        self.chown = chown or shutil.chown

    @staticmethod
    def _run(command):
        return subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )

    @staticmethod
    def _restart():
        result = subprocess.run(
            ["systemctl", "restart", "mosquitto"],
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
        return result.returncode == 0

    def config_text(self):
        return (
            "per_listener_settings false\n"
            "allow_anonymous false\n"
            f"password_file {self.password_file}\n"
            f"acl_file {self.acl_file}\n\n"
            "# Home Assistant, Controller and local Agent use loopback.\n"
            "listener 1883 127.0.0.1\n"
        )

    @staticmethod
    def _snapshot(path):
        if not path.exists():
            return None
        metadata = path.stat()
        return {
            "content": path.read_bytes(),
            "mode": stat.S_IMODE(metadata.st_mode),
            "uid": metadata.st_uid,
            "gid": metadata.st_gid,
        }

    @staticmethod
    def _atomic_write(path, content, mode):
        path.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary_name = tempfile.mkstemp(
            dir=path.parent,
            prefix=f".{path.name}.",
        )
        temporary = Path(temporary_name)
        try:
            with os.fdopen(descriptor, "wb") as output:
                output.write(content)
                output.flush()
                os.fsync(output.fileno())
            os.chmod(temporary, mode)
            os.replace(temporary, path)
        except Exception:
            temporary.unlink(missing_ok=True)
            raise

    def _restore(self, snapshots):
        for path, snapshot in snapshots.items():
            if snapshot is None:
                path.unlink(missing_ok=True)
                continue
            self._atomic_write(path, snapshot["content"], snapshot["mode"])
            os.chown(path, snapshot["uid"], snapshot["gid"])

    def _prepare_password_file(self, target, credentials):
        if self.password_file.exists():
            shutil.copy2(self.password_file, target)
        for index, username in enumerate(sorted(credentials)):
            _username(username, "credential username")
            password = credentials[username]
            if (
                not isinstance(password, str)
                or not password
                or len(password) > 512
                or "\n" in password
                or "\r" in password
            ):
                raise BrokerPolicyError("credential password is invalid")
            command = ["mosquitto_passwd", "-b"]
            if not target.exists() and index == 0:
                command.append("-c")
            command.extend([str(target), username, password])
            result = self.runner(command)
            if getattr(result, "returncode", 1) != 0:
                raise BrokerPolicyError(
                    f"mosquitto_passwd failed for username {username!r}"
                )
        if not target.exists():
            raise BrokerPolicyError(
                "password file does not exist and no credentials were supplied"
            )

    def apply(self, *, credentials, acl_text):
        if not isinstance(credentials, dict):
            raise BrokerPolicyError("credentials must be an object")
        if not isinstance(acl_text, str) or not acl_text.strip():
            raise BrokerPolicyError("acl_text must not be empty")

        self.password_file.parent.mkdir(parents=True, exist_ok=True)
        lock_path = self.password_file.parent / ".vps-sentinel-broker.lock"
        snapshots = {
            self.password_file: self._snapshot(self.password_file),
            self.acl_file: self._snapshot(self.acl_file),
            self.config_file: self._snapshot(self.config_file),
        }
        with lock_path.open("a+b") as lock:
            fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
            with tempfile.TemporaryDirectory(
                dir=self.password_file.parent,
                prefix=".vps-sentinel-broker.",
            ) as staging_name:
                staging = Path(staging_name)
                staged_password = staging / "passwd"
                self._prepare_password_file(staged_password, credentials)
                staged_acl = acl_text.encode("utf-8")
                staged_config = self.config_text().encode("utf-8")
                try:
                    self._atomic_write(
                        self.password_file,
                        staged_password.read_bytes(),
                        0o640,
                    )
                    self._atomic_write(self.acl_file, staged_acl, 0o640)
                    self._atomic_write(self.config_file, staged_config, 0o644)
                    self.chown(
                        self.password_file,
                        user="root",
                        group="mosquitto",
                    )
                    self.chown(
                        self.acl_file,
                        user="root",
                        group="mosquitto",
                    )
                    if not self.restarter():
                        raise BrokerPolicyError(
                            "Mosquitto restart failed; original files restored"
                        )
                except Exception:
                    self._restore(snapshots)
                    self.restarter()
                    raise
        return True
